In [4]:
import numpy as np
import pandas as pd

best practices:
1. preprocessing
2. train test split
3. bow,tfidf, word2vec
4. train ml algo

In [5]:
df = pd.read_csv(r"C:\Users\symni\Desktop\Data Science motes and resources- Krish naik\NLP\all_kindle_review.csv")

In [6]:
df

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0                 0       11539  B0033UV8HI  [8, 10]       3   
1                 1        5957  B002HJV4DE   [1, 1]       5   
2                 2        9146  B002ZG96I4   [0, 0]       3   
3                 3        7038  B002QHWOEU   [1, 3]       3   
4                 4        1776  B001A06VJ8   [0, 1]       4   
...             ...         ...         ...      ...     ...   
11995         11995        2183  B001DUGORO   [0, 0]       4   
11996         11996        6272  B002JCSFSQ   [2, 2]       5   
11997         11997       12483  B0035N1V7K   [0, 1]       3   
11998         11998        3640  B001W1XT40   [1, 2]       1   
11999         11999       11398  B003370JUS   [5, 6]       3   

                                              reviewText   reviewTime  \
0      Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1      Great short read.  I didn't want to put it dow...   10 8, 2013   
2      I'll start by saying this is the first of four...  04 11, 2014   
3      Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4      I did not expect this type of book to be in li...  12 31, 2012   
...                                                  ...          ...   
11995  Valentine cupid is a vampire- Jena and Ian ano...  02 28, 2014   
11996  I have read all seven books in this series. Ap...  05 16, 2011   
11997  This book really just wasn't my cuppa.  The si...  07 26, 2013   
11998  tried to use it to charge my kindle, it didn't...  09 17, 2013   
11999  Taking Instruction is a look into the often hi...   07 5, 2012   

           reviewerID                   reviewerName  \
0      A3HHXRELK8BHQG                         Ridley   
1      A2RGNZ0TRF578I                   Holly Butler   
2      A3S0H2HV6U1I7F                        Merissa   
3       AC4OQW3GZ919J                     Cleargrace   
4      A3C9V987IQHOQD                       Rjostler   
...               ...                            ...   
11995  A1OKS5Q1HD8WQC                  lisa jon jung   
11996   AQRSPXLNEQAMA                        TerryLP   
11997  A2T5QLT5VXOJAK                        hwilson   
11998  A28MHD2DDY6DXB  Allison A. Slater "Gryphon50"   
11999  A3JUXLB4K9ZXCC                      Dafna Yee   

                                                 summary  unixReviewTime  
0                               Entertaining But Average      1283385600  
1                                Terrific menage scenes!      1381190400  
2                                       Snapdragon Alley      1397174400  
3                                 very light murder cozy      1404518400  
4                                                   Book      1356912000  
...                                                  ...             ...  
11995                                               jena      1393545600  
11996                                Peacekeepers Series      1305504000  
11997                                    a little creepy      1374796800  
11998                                        didn't work      1379376000  
11999  If you like BDSM with a touch of romance, this...      1341446400  

[12000 rows x 11 columns]

In [7]:
# i only need the columns reviews and ratings from df
df1 = df[['reviewText','rating']]

In [8]:
df1.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [9]:
df1.shape

(12000, 2)

In [10]:
df1.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [11]:
df1['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [12]:
df1['rating'].value_counts()

5    3000
4    3000
3    2000
2    2000
1    2000
Name: rating, dtype: int64

### Preprocessing

In [13]:
#we need to categorize based on the ratings to identify which is negative positive, mid

In [14]:
#this is like case statement in sql .apply()

In [16]:
df1['rating']=df1['rating'].apply( lambda x :0 if x<3 else 1)

C:\Users\symni\AppData\Local\Temp\ipykernel_2860\2212879288.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['rating']=df1['rating'].apply( lambda x :0 if x<3 else 1)


In [17]:
df1.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [19]:
df1['rating'].value_counts() # we cna see the values are almost imbaalanced but not because atleast half of its there. if its les than half we can say its imabalanced

1    8000
0    4000
Name: rating, dtype: int64

###1.lowercase

In [21]:
df1['reviewText']=df1['reviewText'].str.lower()

C:\Users\symni\AppData\Local\Temp\ipykernel_2860\1787039203.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['reviewText']=df1['reviewText'].str.lower()


In [22]:
df1

reviewText  rating
0      jace rankin may be short, but he's nothing to ...       1
1      great short read.  i didn't want to put it dow...       1
2      i'll start by saying this is the first of four...       1
3      aggie is angela lansbury who carries pocketboo...       1
4      i did not expect this type of book to be in li...       1
...                                                  ...     ...
11995  valentine cupid is a vampire- jena and ian ano...       1
11996  i have read all seven books in this series. ap...       1
11997  this book really just wasn't my cuppa.  the si...       1
11998  tried to use it to charge my kindle, it didn't...       0
11999  taking instruction is a look into the often hi...       1

[12000 rows x 2 columns]

In [27]:
import re
import nltk
from nltk.corpus import stopwords
from bs4 import BeautifulSoup
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\symni\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [32]:
## Removing special characters
df1['reviewText']=df1['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df1['reviewText']=df1['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url 
df1['reviewText']=df1['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df1['reviewText']=df1['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df1['reviewText']=df1['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\symni\AppData\Local\Temp\ipykernel_2860\1980268792.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['reviewText']=df1['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
C:\Users\symni\AppData\Local\Temp\ipykernel_2860\1980268792.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['reviewText']=df1['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
C:\Users\symni\AppData\Local\Temp\ipykernel_2860\1980268792.py:6: SettingWithCo

In [35]:
df1.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [40]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [41]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [43]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

In [44]:
### Train test split

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(df['reviewText'],df['rating'],test_size=0.2, random_state = 42)

In [54]:
from sklearn.feature_extraction.text import CountVectorizer
bow =CountVectorizer()
X_train_bow =bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tf =bow.fit_transform(X_train).toarray()
X_test_tf = bow.transform(X_test).toarray()

In [56]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Model training

In [57]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tf,y_train)

In [58]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [59]:
y_pred_bow =nb_model_bow.predict(X_test_bow)
y_pred_tfidf =nb_model_bow.predict(X_test_tf)

In [60]:
print(accuracy_score(y_test,y_pred_bow))

0.2791666666666667


In [61]:
print(confusion_matrix(y_test,y_pred_bow))

[[188  78  53  55  30]
 [155  76  54  67  47]
 [114  74  71  74  54]
 [183  74  75 161  94]
 [170  84  86 109 174]]


In [63]:
print(accuracy_score(y_test,y_pred_tfidf))

0.2791666666666667
